# Runs docker images from docker hub repository.
version: "3.3"
services:
  personal_website:
    image: roysalazarportilla/personal_website:latest
    restart: on-failure
    env_file:
      - /etc/environment
    container_name: personal_website
    networks:
      - my-network
networks:
  my-network:
    external: true