version: "3.3"
services:  
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    volumes:
      - ./nginx/configs/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'
    container_name: nginx
    networks:
      - portfolio-network
networks:
  portfolio-network:
    external: true