version: "3.3"
services:  
  portfolio_entry_ui-test:
    build:
      context: ./ui
      dockerfile: Dockerfile.dev.test
    volumes:
      - ./ui:/app
      - /app/node_modules
    restart: always
    container_name: portfolio_entry_ui-test