version: "3.3"
services:  
  personal_website:
    build:
      context: ./ui
      dockerfile: Dockerfile.dev
    volumes:
      - ./ui:/app
      - /app/.next
      - /app/node_modules
    ports:
      - '5000:5000'
    restart: on-failure
    container_name: personal_website