version: "3.3"
services:  
  personal_website-test:
    build:
      context: ./ui
      dockerfile: Dockerfile.dev.test
    volumes:
      - ./ui:/app
      - /app/node_modules
    restart: always
    container_name: personal_website-test