version: "3.3"
services:  
  portfolio_entry_nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    volumes:
      - ./nginx/configs/dev/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'
    container_name: portfolio_entry_nginx
    networks:
      - portfolio-network
  portfolio_entry_ui:
    build:
      context: ./ui
      dockerfile: Dockerfile.dev
    volumes:
      - ./ui:/app
      - /app/.next
      - /app/node_modules
    restart: on-failure
    container_name: portfolio_entry_ui
    networks:
      - portfolio-network
networks:
  portfolio-network:
    external: true