# Runs docker images from docker hub repository.
version: "3.3"
services:
  portfolio_entry_nginx-reverse-proxy:
    image: roysalazarportilla/portfolio_entry_nginx-reverse-proxy:latest
    restart: always
    ports:
      - '80:80'
    container_name: portfolio_entry_nginx-reverse-proxy
    networks:
      - portfolio-network
  portfolio_entry_ui:
    image: roysalazarportilla/portfolio_entry_ui:latest
    restart: on-failure
    env_file:
      - /etc/environment
    container_name: portfolio_entry_ui
    networks:
      - portfolio-network
networks:
  portfolio-network:
    external: true